spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: kimho
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true