spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url:
      jdbc: ${JDBC_DATABASE_URL:}
    driver-class-name: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    port: ${PORT:5000}
jwt-key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJCbG9nIn0.ucIV1H5LjsmblZKyeiz39H1EYsNXZ9tM9PD1qKVMe1lmtpqP0L6eyQhd7I_xsmvB32TcG6h6mg1zwcn6bv3kMg